"""empty message

Revision ID: 0001
Revises: 
Create Date: 2025-12-23 21:36:53.372764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system_number', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Признак удаления'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Дата удаления'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_claims'))
    )
    op.create_index(op.f('ix_claim_claims_created_at'), 'claim_claims', ['created_at'], unique=False)
    op.create_index(op.f('ix_claim_claims_is_deleted'), 'claim_claims', ['is_deleted'], unique=False)
    op.create_table('claim_payment_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Признак удаления'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Дата удаления'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.ForeignKeyConstraint(['claim_id'], ['claim_claims.id'], name=op.f('fk_claim_payment_items_claim_id_claim_claims')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_payment_items'))
    )
    op.create_index(op.f('ix_claim_payment_items_claim_id'), 'claim_payment_items', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_payment_items_created_at'), 'claim_payment_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_claim_payment_items_is_deleted'), 'claim_payment_items', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_payment_items_is_deleted'), table_name='claim_payment_items')
    op.drop_index(op.f('ix_claim_payment_items_created_at'), table_name='claim_payment_items')
    op.drop_index(op.f('ix_claim_payment_items_claim_id'), table_name='claim_payment_items')
    op.drop_table('claim_payment_items')
    op.drop_index(op.f('ix_claim_claims_is_deleted'), table_name='claim_claims')
    op.drop_index(op.f('ix_claim_claims_created_at'), table_name='claim_claims')
    op.drop_table('claim_claims')
    # ### end Alembic commands ###
